//Create a user
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "sambo3",
    "email": "sambo3@gmail.com",
    "password": "1234",
    "confPassword": "1234"

}

###
//get All user
GET http://localhost:5000/users

###
//get single user
GET http://localhost:5000/users/2a21f8f0-9293-4a99-a519-c489fe3e7874

###
//update user
PATCH http://localhost:5000/users/2a21f8f0-9293-4a99-a519-c489fe3e7874
Content-Type: application/json

{
    "name": "admin",
    "email": "admin@gmail.com",
    "password": "1234",
    "confPassword": "1234"
}

###
//delete a user
DELETE http://localhost:5000/users/2a21f8f0-9293-4a99-a519-c489fe3e7874

###
//Login admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "1234"
}

###
//Login User
POST http://localhost:5000/login
Content-Type: application/json

{
    
    "email": "sambo3@gmail.com",
    "password": "1234"
    

}

###
GET http://localhost:5000/me

###
//logout
DELETE  http://localhost:5000/logout

//search product
###
GET http://localhost:5000/products?search_query=category&page=0&limit=10

//get All Product
###
POST http://localhost:5000/products

###
//get Product User
POST http://localhost:5000/productUser

###
//create transaction
POST http://localhost:5000/checkout
Content-Type: application/json
{
    "name": "rudi",
    "address": "solo",
    "phone": "08995232430",
    "note": "tolong cepat dikirim",
    "order": "2"

}

###
//get All transaction
GET http://localhost:5000/checkout

###
//get transaction user
GET http://localhost:5000/checkout

###
//update transaction user
PATCH  http://localhost:5000/checkout/9907c516-a6f1-4a53-94b3-0d6f2b635f3e
Content-Type: application/json
{
    "name": "putin",
    "address": "solo",
    "phone": "08995232430",
    "note": "tolong cepat dikirim",
    "order": "2"

}

###
DELETE http://localhost:5000/checkout/c0425418-411e-41c9-bb19-acc683ca6821

